'use client';

import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { FileText, Trophy, Video, Camera, Search, PlayCircle, Users, ChevronDown, ExternalLink } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';

// Import the data generated by your script
import { gallery2025Data, GalleryItem } from '@/lib/gallery2025-manifest';

type CompetitionTeamMember = {
  name: string;
  photoUrl: string;
  hint: string;
  rotation?: number;
};

// Use the imported data
const gallery2025: GalleryItem[] = gallery2025Data || [];

const competitionTeam2025: CompetitionTeamMember[] = [
  {
    name: 'Analía Díaz',
    photoUrl: '/Analia_Management2025.webp',
    hint: 'team lead at competition',
    rotation: 0
  },
  {
    name: 'Anibal Rosado',
    photoUrl: '/Anibal_Mechanical2025.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'David A. Torres',
    photoUrl: '/David_Mechanical2025.webp',
    hint: 'team member working on robot',
    rotation: 0
  },
  {
    name: 'Elian E. Soto',
    photoUrl: '/Elian_Software.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Javier Rivera',
    photoUrl: '/Javier_Software2025.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Mia S. Figueroa',
    photoUrl: '/Mia_Electrical2025.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Ricardo G. Perez',
    photoUrl: '/Ricardo_Mechanical2025.webp',
    hint: 'team member at poolside',
    rotation: 0
  },
  {
    name: 'Victor O. Riefkohl',
    photoUrl: '/Victor_Electrical2025.webp',
    hint: 'team member with electronics',
    rotation: 0
  },
];

const gallery2024: any[] = [
  {
    src: '/robosub_2024_1.mp4',
    hint: 'RoboSub 2024 recap video',
    type: 'video',
  },
  {
    src: '/robosub_2024_2.jpg',
    hint: 'underwater robot action',
    type: 'image',
  },
  {
    src: '/robosub_2024_3.mp4',
    hint: 'team working robot',
    type: 'video',
  },
  {
    src: '/robosub_2024_4.jpg',
    hint: 'team celebrating success',
    type: 'image',
  },
  {
    src: '/robosub_2024_5.jpg',
    hint: 'team at competition',
    type: 'image',
  },
  {
    src: '/robosub_2024_6.jpg',
    hint: 'robot performing tasks',
    type: 'image',
  },
  {
    src: '/robosub_2024_7.jpg',
    hint: 'team strategizing',
    type: 'image',
  },
  {
    src: '/robosub_2024_8.jpg',
    hint: 'robot in action',
    type: 'image',
  },
  {
    src: '/robosub_2024_9.jpg',
    hint: 'team celebrating success',
    type: 'image',
  },
  {
    src: '/robosub_2024_10.mp4',
    hint: 'team celebrating victory',
    type: 'video',
  },
  {
    src: '/robosub_2024_11.jpg',
    hint: 'team celebrating victory',
    type: 'image',
  },
  {
    src: '/robosub_2024_12.mp4',
    hint: 'team celebrating victory',
    type: 'video',
  }
];

const competitionTeam2024: CompetitionTeamMember[] = [
  {
    name: 'Ordep Agustín',
    photoUrl: '/Ordep.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Anibal Rosado',
    photoUrl: '/Anibal_Mechanical2025.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Victor O. Riefkohl',
    photoUrl: '/victor.webp',
    hint: 'team member with electronics',
    rotation: 0
  },
  {
    name: 'Analía Díaz',
    photoUrl: '/Analia.webp',
    hint: 'team lead at competition',
    rotation: 90
  },
  {
    name: 'Angel Cintrón',
    photoUrl: '/angel.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Ronald R. Bosques',
    photoUrl: '/Ronald.webp',
    hint: 'team member at competition',
    rotation: 90
  },
  {
    name: 'Gabriela David',
    photoUrl: '/Gabriela.webp',
    hint: 'team member at competition',
    rotation: 90
  },
  {
    name: 'Alejandro González',
    photoUrl: '/alejandro.webp',
    hint: 'team member at competition',
    rotation: 0
  },
  {
    name: 'Joshua Camacho',
    photoUrl: '/Tarzan_ImageMissing.webp',
    hint: 'team member at poolside',
    rotation: 0
  }
];

const ITEMS_PER_PAGE = 12;

export default function CompetitionPage() {
  const [selectedItem, setSelectedItem] = useState<GalleryItem | null>(null);
  const [visibleCount, setVisibleCount] = useState(ITEMS_PER_PAGE);

  const handleLoadMore = () => {
    setVisibleCount((prev) => prev + ITEMS_PER_PAGE);
  };

  return (
    <>
      <div className="min-h-screen bg-black text-white">
        <div className="container mx-auto px-4 py-16">
          {/* Hero Section */}
          <div className="text-center mb-16 relative">
            <div className="absolute -top-10 left-1/2 transform -translate-x-1/2 w-32 h-32 bg-[#00A68C]/10 rounded-full blur-3xl"></div>
            
            <h1 className="font-anton text-4xl md:text-5xl lg:text-6xl font-bold mb-6 tracking-wide">
              <span className="bg-gradient-to-r from-[#1FB355] via-[#51DFC9] to-white bg-clip-text text-transparent">
                COMPETITION JOURNEY
              </span>
            </h1>
            
            <p className="font-roboto text-lg text-gray-300 max-w-3xl mx-auto leading-relaxed">
              Following our path through the annual RoboSub competition, where innovation meets the deep blue.
            </p>
          </div>

          {/* RoboSub 2025 Section */}
          <section id="robosub2025" className="mb-20">
            <div className="relative mb-10">
              <div className="absolute -left-4 top-1/2 transform -translate-y-1/2 w-1 h-16 bg-gradient-to-b from-[#00A68C] to-[#51DFC9]"></div>
              <h2 className="font-anton text-3xl md:text-4xl font-bold ml-8 tracking-wide text-white">ROBOSUB 2025</h2>
              <p className="font-roboto text-[#51DFC9] ml-8 mt-2 text-lg">Our focus for the current season</p>
            </div>

            <div className="space-y-16">
              {/* Strategy Card */}
              <div className="bg-[#1a1d1d] rounded-2xl p-8 shadow-xl border border-[#00A68C]/20">
                <div className="flex items-center gap-4 mb-6">
                  <h3 className="font-anton text-2xl font-bold text-white tracking-wide">OUR 2025 STRATEGY</h3>
                </div>
                
                <p className="font-roboto text-gray-300 max-w-4xl leading-relaxed">
                  This year, our strategy revolves around enhancing our AUV's perception and decision-making capabilities. 
                  We are implementing a new multi-sensor fusion algorithm and a more robust mission planner to tackle the 
                  complex tasks of RoboSub 2025. Our mechanical design features a modular system for quick adjustments 
                  and repairs during the competition.
                </p>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-col sm:flex-row gap-4">
                <Button asChild size="lg" className="group">
                  <Link 
                    href="https://youtu.be/70T9lQ628FE?si=KQOwplWlAgWRpmTj" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="gap-3 font-roboto font-medium bg-gradient-to-r from-[#00A68C] to-[#51DFC9] hover:from-[#00A68C] hover:to-[#1FB355] text-white px-8 py-6 rounded-xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1"
                  >
                    <Video className="h-5 w-5" />
                    <span>Team Video 2025</span>
                    <ExternalLink className="h-4 w-4 opacity-0 group-hover:opacity-100 group-hover:translate-x-1 transition-all duration-300" />
                  </Link>
                </Button>
                <Button asChild size="lg" className="group bg-[#00A68C] hover:bg-[#51DFC9] text-white border-none shadow-lg hover:shadow-xl transition-all duration-300">
                  <a 
                    href="/TDR_UPRM_RUMarino_RS2025.pdf" 
                    download="Rumarino-TDR-2025.pdf"
                    className="gap-3 font-roboto font-bold bg-gradient-to-r from-[#1FB355] to-[#00A68C] hover:from-[#00A68C] hover:to-[#51DFC9] text-white px-6 py-4 rounded-xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1"
                  >
                    <FileText className="h-5 w-5" />
                    <span>Download TDR 2025</span>
                  </a>
                </Button>
              </div>

              {/* Team Squad 2025 */}
              <div className="bg-[#1a1d1d] rounded-2xl p-8 shadow-xl border border-[#00A68C]/20">
                <div className="flex items-center gap-4 mb-8">
                  <div>
                    <h3 className="font-anton text-2xl font-bold text-white tracking-wide">OUR 2025 COMPETITION SQUAD</h3>
                    <p className="font-roboto text-[#51DFC9]">The faces behind the innovation</p>
                  </div>
                </div>
                
                <p className="font-roboto text-gray-300 mb-8 max-w-4xl">
                  The team for RoboSub 2025 is forming. Check back for updates on the members who will represent RUMarino in the upcoming competition.
                </p>
                
                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-8">
                  {competitionTeam2025.map((member) => (
                    <div key={member.name} className="group text-center flex flex-col items-center">
                      <div className="relative w-32 h-32 md:w-36 md:h-36 mb-4 overflow-visible">
                        <div className="absolute -inset-2 bg-gradient-to-r from-[#00A68C] to-[#51DFC9] rounded-full opacity-0 group-hover:opacity-100 blur-md transition-opacity duration-500"></div>
                        <div className="relative w-full h-full">
                          <Image
                            src={member.photoUrl}
                            alt={`Photo of ${member.name}`}
                            fill
                            className="object-cover rounded-full shadow-lg border-2 border-[#171919] group-hover:border-[#00A68C] transition-all duration-300 group-hover:scale-105"
                            style={{ transform: `rotate(${member.rotation || 0}deg)` }}
                            data-ai-hint={member.hint}
                          />
                        </div>
                      </div>
                      <h4 className="font-roboto font-semibold text-base text-white group-hover:text-[#51DFC9] transition-colors duration-300">
                        {member.name}
                      </h4>
                    </div>
                  ))}
                </div>
              </div>

              {/* Gallery 2025 */}
              <div className="bg-[#1a1d1d] rounded-2xl p-8 shadow-xl border border-[#00A68C]/20">
                <div className="flex items-center justify-between mb-8">
                  <div className="flex items-center gap-4">
                    <div className="bg-gradient-to-r from-[#00A68C] to-[#51DFC9] w-12 h-12 rounded-xl flex items-center justify-center">
                      <Camera className="h-6 w-6 text-white" />
                    </div>
                    <div>
                      <h3 className="font-anton text-2xl font-bold text-white tracking-wide">COMPETITION GALLERY 2025</h3>
                      <p className="font-roboto text-[#51DFC9]">
                        <span suppressHydrationWarning>
                          {gallery2025.length} moments captured
                        </span>
                      </p>
                    </div>
                  </div>
                </div>
                
                {gallery2025.length === 0 ? (
                  <div className="text-center py-12">
                    <p className="font-roboto text-[#51DFC9] text-lg">Gallery updates coming soon. Stay tuned!</p>
                  </div>
                ) : (
                  <>
                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                      {gallery2025.slice(0, visibleCount).map((item) => (
                        <div
                          key={item.src}
                          className="group relative aspect-square rounded-xl overflow-hidden cursor-pointer bg-[#171919] border border-[#51DFC9]/10 hover:border-[#00A68C] transition-all duration-300 hover:shadow-2xl"
                          onClick={() => setSelectedItem(item)}
                        >
                          <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                          
                          {item.type === 'video' ? (
                            <video
                              src={item.src}
                              className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                              muted
                              loop
                              playsInline
                              onMouseEnter={(e) => e.currentTarget.play()}
                              onMouseLeave={(e) => e.currentTarget.pause()}
                            />
                          ) : (
                            <Image
                              src={item.src}
                              alt={item.hint}
                              fill
                              loading="lazy"
                              sizes="(max-width: 768px) 50vw, 25vw"
                              className="object-cover transition-transform duration-500 group-hover:scale-110"
                              data-ai-hint={item.hint}
                            />
                          )}
                          
                          <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                            <div className="bg-[#171919]/80 backdrop-blur-sm p-4 rounded-full">
                              {item.type === 'video' ? (
                                <PlayCircle className="h-10 w-10 text-[#51DFC9]" />
                              ) : (
                                <Search className="h-8 w-8 text-[#51DFC9]" />
                              )}
                            </div>
                          </div>
                          
                          <div className="absolute bottom-0 left-0 right-0 p-3 bg-gradient-to-t from-[#171919] to-transparent transform translate-y-full group-hover:translate-y-0 transition-transform duration-300">
                            <p className="font-roboto text-white text-sm truncate">{item.hint}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                    
                    {visibleCount < gallery2025.length && (
                      <div className="mt-10 text-center">
                        <Button 
                          variant="outline" 
                          size="lg" 
                          onClick={handleLoadMore}
                          className="group font-roboto font-medium border-[#51DFC9]/30 hover:border-[#00A68C] text-[#51DFC9] hover:text-white px-8 py-6 rounded-xl"
                        >
                          <ChevronDown className="mr-2 h-5 w-5 group-hover:animate-bounce" />
                          Load More ({gallery2025.length - visibleCount} remaining)
                        </Button>
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>
          </section>

          {/* Separator */}
          <div className="relative my-16">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-[#00A68C]/30"></div>
            </div>
            <div className="relative flex justify-center">
              <div className="bg-gradient-to-r from-[#00A68C] to-[#51DFC9] px-6 py-2 rounded-full text-white font-roboto font-bold text-sm tracking-wide">
                2024 → 2025
              </div>
            </div>
          </div>

          {/* RoboSub 2024 Section */}
          <section id="robosub2024" className="mb-20">
            <div className="relative mb-10">
              <div className="absolute -left-4 top-1/2 transform -translate-y-1/2 w-1 h-16 bg-gradient-to-b from-[#1FB355] to-[#51DFC9]"></div>
              <h2 className="font-anton text-3xl md:text-4xl font-bold ml-8 tracking-wide text-white">ROBOSUB 2024</h2>
              <p className="font-roboto text-[#1FB355] ml-8 mt-2 text-lg">A look back at our performance last year</p>
            </div>

            {/* Hero Image */}
            <div className="relative aspect-video w-full overflow-hidden rounded-2xl shadow-2xl mb-12 group">
              <Image 
                src="https://i.ytimg.com/vi/zGQymhIOxDs/maxresdefault.jpg" 
                alt="RoboSub 2024 Team" 
                fill 
                className="object-cover transition-transform duration-700 group-hover:scale-105" 
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#171919]/80 via-transparent to-transparent"></div>
              <div className="absolute bottom-0 left-0 right-0 p-8">
                <h3 className="font-anton text-2xl font-bold text-white mb-2 tracking-wide">TEAM RUMARINO AT ROBOSUB 2024</h3>
                <p className="font-roboto text-[#51DFC9]">Memories from San Diego, California</p>
              </div>
            </div>

            <div className="space-y-16">
              {/* Action Buttons */}
              <div className="flex flex-col sm:flex-row gap-4">
                {/* Watch Button */}
                <Button asChild size="lg" className="group">
                  <Link
                    href="https://youtu.be/ZnLuskI1WZ4?si=vJ_sxa-QWqNXXmte"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="gap-3 font-roboto font-medium bg-gradient-to-r from-[#00A68C] to-[#51DFC9] hover:from-[#00A68C] hover:to-[#1FB355] text-white px-8 py-6 rounded-xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1"
                  >
                    <Video className="h-5 w-5" />
                    <span>Watch 2024 Recap</span>
                    <ExternalLink className="h-4 w-4 opacity-0 group-hover:opacity-100 group-hover:translate-x-1 transition-all duration-300" />
                  </Link>
                </Button>

                {/* View Button */}
                <Button
                  asChild
                  size="lg"
                  variant="outline"
                  className="group border-[#51DFC9]/30 hover:border-[#1FB355] bg-transparent"
                >
                  <Link
                    href="/RUMarino TDR 2024.pdf"
                    className="gap-3 font-roboto font-bold bg-gradient-to-r from-[#1FB355] to-[#00A68C] hover:from-[#00A68C] hover:to-[#51DFC9] text-white px-6 py-4 rounded-xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1"
                  >
                    <FileText className="h-5 w-5" />
                    <span>View 2024 TDR</span>
                  </Link>
                </Button>
              </div>

              {/* Team Squad 2024 */}
              <div className="bg-[#1a1d1d] rounded-2xl p-8 shadow-xl border border-[#1FB355]/20">
                <div className="flex items-center gap-4 mb-8">
                  <div>
                    <h3 className="font-anton text-2xl font-bold text-white tracking-wide">OUR 2024 COMPETITION SQUAD</h3>
                    <p className="font-roboto text-[#51DFC9]">The champions who made it happen</p>
                  </div>
                </div>
                
                <p className="font-roboto text-gray-300 mb-8 max-w-4xl">
                  Meet the dedicated members who represented RUMarino at RoboSub 2024. Their hard work and collaboration 
                  on-site were key to our performance. Below is a look at who was there and the crucial roles they played 
                  during the intense competition week.
                </p>
                
                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-8">
                  {competitionTeam2024.map((member) => (
                    <div key={member.name} className="group text-center flex flex-col items-center">
                      <div className="relative w-32 h-32 md:w-36 md:h-36 mb-4 overflow-visible">
                        <div className="absolute -inset-2 bg-gradient-to-r from-[#1FB355] to-[#51DFC9] rounded-full opacity-0 group-hover:opacity-100 blur-md transition-opacity duration-500"></div>
                        <div className="relative w-full h-full">
                          <Image
                            src={member.photoUrl}
                            alt={`Photo of ${member.name}`}
                            fill
                            className="object-cover rounded-full shadow-lg border-2 border-[#171919] group-hover:border-[#1FB355] transition-all duration-300 group-hover:scale-105"
                            style={{ transform: `rotate(${member.rotation || 0}deg)` }}
                            data-ai-hint={member.hint}
                          />
                        </div>
                      </div>
                      <h4 className="font-roboto font-semibold text-base text-white group-hover:text-[#51DFC9] transition-colors duration-300">
                        {member.name}
                      </h4>
                    </div>
                  ))}
                </div>
              </div>

              {/* Gallery 2024 */}
              <div className="bg-[#1a1d1d] rounded-2xl p-8 shadow-xl border border-[#1FB355]/20">
                <div className="flex items-center gap-4 mb-8">
                  <div className="bg-gradient-to-r from-[#00A68C] to-[#51DFC9] w-12 h-12 rounded-xl flex items-center justify-center">
                    <Camera className="h-6 w-6 text-white" />
                  </div>
                  <div>
                    <h3 className="font-anton text-2xl font-bold text-white tracking-wide">COMPETITION GALLERY 2024</h3>
                    <p className="font-roboto text-[#51DFC9]">Memories from the competition floor</p>
                  </div>
                </div>
                
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                  {gallery2024.map((item, idx) => (
                    <div
                      key={idx}
                      className="group relative aspect-square rounded-xl overflow-hidden cursor-pointer bg-[#171919] border border-[#51DFC9]/10 hover:border-[#1FB355] transition-all duration-300 hover:shadow-2xl"
                      onClick={() => setSelectedItem(item)}
                    >
                      <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                      
                      {item.type === 'video' ? (
                        <video
                          src={item.src}
                          className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                          muted
                          loop
                          onMouseEnter={(e) => e.currentTarget.play()}
                          onMouseLeave={(e) => e.currentTarget.pause()}
                        />
                      ) : (
                        <Image
                          src={item.src}
                          alt={`RoboSub 2024 gallery item ${idx + 1}`}
                          fill
                          className="object-cover transition-transform duration-500 group-hover:scale-110"
                          data-ai-hint={item.hint}
                        />
                      )}
                      
                      <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                        <div className="bg-[#171919]/80 backdrop-blur-sm p-4 rounded-full">
                          {item.type === 'video' ? (
                            <PlayCircle className="h-10 w-10 text-[#51DFC9]" />
                          ) : (
                            <Search className="h-8 w-8 text-[#51DFC9]" />
                          )}
                        </div>
                      </div>
                      
                      <div className="absolute bottom-0 left-0 right-0 p-3 bg-gradient-to-t from-[#171919] to-transparent transform translate-y-full group-hover:translate-y-0 transition-transform duration-300">
                        <p className="font-roboto text-white text-sm truncate">{item.hint}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>

      {/* Modal for Expanded View */}
      <Dialog
        open={!!selectedItem}
        onOpenChange={(isOpen) => {
          if (!isOpen) {
            setSelectedItem(null);
          }
        }}
      >
        <DialogContent className="max-w-5xl w-full p-0 border-0 bg-transparent shadow-none">
          <DialogHeader className="sr-only">
            <DialogTitle>Expanded Media View</DialogTitle>
          </DialogHeader>
          {selectedItem && (
            <div className="relative">
              {selectedItem.type === 'image' ? (
                <Image
                  src={selectedItem.src}
                  alt={selectedItem.hint}
                  width={1200}
                  height={800}
                  className="w-full h-auto max-h-[85vh] object-contain rounded-2xl shadow-2xl"
                  data-ai-hint={selectedItem.hint}
                />
              ) : (
                <video
                  src={selectedItem.src}
                  controls
                  autoPlay
                  className="w-full h-auto max-h-[85vh] object-contain rounded-2xl shadow-2xl"
                />
              )}
              <div className="absolute bottom-6 left-1/2 transform -translate-x-1/2">
                <span className="font-roboto bg-[#171919]/80 backdrop-blur-sm px-4 py-2 rounded-full text-[#51DFC9] text-sm">
                  {selectedItem.hint}
                </span>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}